# Site settings
title: Pixelite
email: admin@pixelite.co.nz
description: "A technology blog or rant area depending on the topic"
baseurl: ""
url: "http://www.pixelite.co.nz"
twitter_username: pixelite_
github_username:  pixelite-co-nz
facebook_username:

# Build settings
markdown: kramdown
permalink: /article/:title
paginate: 21
exclude: ["node_modules"]
highlighter: pygments


# Image settings
mini_magick:
    thumbnail:
        source: "img"
        destination: "img/thumbnail"
        resize: "640x480"